name: Check Ticket

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Run Ticket Monitor
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: ${{ secrets.MELON_EVENT_ID }}
          slack-incoming-webhook-url: ${{ secrets.NOTIFIER_SLACK_WEBHOOK_URL }}
          telegram-bot-token: ${{ secrets.NOTIFIER_TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.NOTIFIER_TELEGRAM_CHAT_ID }}
